package constants

/* const (
	ToolName                    = "fastdeploy"
	DeploymentRepositoryVersion = "deployment_repository_version"
	DeploymentRepositoryUrl     = "deployment_repository_url"
	DeploymentRepositoryName    = "deployment_repository_name"
	DeploymentRepositoryPath    = "deployment_repository_path"
	DeploymentId                = "deployment_id"
	DeploymentId8               = "deployment_id8"
	DeploymentId12              = "deployment_id12"
	DeploymentId16              = "deployment_id16"
	ProjectOrganization         = "project_organization"
	ProjectTeam                 = "project_team"
	ProjectCategory             = "project_category"
	ProjectName                 = "project_name"
	ProjectName8                = "project_name8"
	ProjectName12               = "project_name12"
	ProjectName16               = "project_name16"
	ProjectId                   = "project_id"
	ProjectId8                  = "project_id8"
	ProjectId12                 = "project_id12"
	ProjectId16                 = "project_id16"
	ProjectVersion              = "project_version"
	ProjectTechnology           = "project_technology"
	ProjectSourcePath           = "project_source_path"
	ProjectType                 = "project_type"
	Environment                 = "environment"
	Environment8                = "environment8"
	Step                        = "step"

	FactoryManual = "manual"
	FactoryIA     = "ia"
)
 */