package template

const DeploymentTemplate = `version: "1.0"
name: "verificacion-herramientas"
description: "Verifica las versiones de Maven y Git"
steps:
  - name: "verificar-maven"
    command: "mvn --version"
    timeout: "30s"
    if: "contains:Apache Maven"
  - name: "verificar-git"
    command: "git -v"
    timeout: "30s"
    if: "contains:git version"
  - name: "verificar-docker"
    command: "docker -v"
    timeout: "30s"
    if: "contains:Docker version"
  - name: "verificar-cambios-git"
    command: "git status -s"
    timeout: "30s"
    if: "empty"
  - name: "clean-package"
    command: "mvn clean package"
    timeout: "5m"
    if: "contains:BUILD SUCCESS"
  - name: "create-container"
    type: "container"
    timeout: "10m"
`
